In [1]:
import pandas as pd
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.drop(['PassengerId', 'Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns', inplace=True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [4]:
target=df.Survived
inputs=df.drop('Survived',axis='columns')

In [7]:
# one hot encoding 
dummies = pd.get_dummies(inputs.Sex, dtype=int)
dummies.head(3)

   female  male
0       0     1
1       1     0
2       1     0

In [8]:
# concat inputs and dummies 
inputs = pd.concat([inputs, dummies], axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female  male
0       3    male  22.0   7.2500       0     1
1       1  female  38.0  71.2833       1     0
2       3  female  26.0   7.9250       1     0

In [9]:
# drop Sex columns
inputs.drop('Sex', axis='columns', inplace=True)
inputs.head(3)

   Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0

In [10]:
# find nan number in any columns
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [11]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [12]:
# use mean to fill those nan values
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(6)

   Pclass        Age     Fare  female  male
0       3  22.000000   7.2500       0     1
1       1  38.000000  71.2833       1     0
2       3  26.000000   7.9250       1     0
3       1  35.000000  53.1000       1     0
4       3  35.000000   8.0500       0     1
5       3  29.699118   8.4583       0     1

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2)

In [25]:
len(X_train)

712

In [26]:
len(X_test)

179

In [27]:
len(inputs)

891

In [28]:
# create naive bayes model
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [29]:
# train the model
model.fit(X_train, y_train)

GaussianNB()

In [30]:
model.score(X_test, y_test)

0.7932960893854749

In [31]:
X_test[:10]

     Pclass        Age      Fare  female  male
110       1  47.000000   52.0000       0     1
870       3  26.000000    7.8958       0     1
730       1  29.000000  211.3375       1     0
316       2  24.000000   26.0000       1     0
621       1  42.000000   52.5542       0     1
454       3  29.699118    8.0500       0     1
426       2  28.000000   26.0000       1     0
345       2  24.000000   13.0000       1     0
230       1  35.000000   83.4750       1     0
872       1  33.000000    5.0000       0     1

In [32]:
y_test[:10]

110    0
870    0
730    1
316    1
621    1
454    0
426    1
345    1
230    1
872    0
Name: Survived, dtype: int64

In [33]:
model.predict(X_test[:10])

array([0, 0, 1, 1, 0, 0, 1, 1, 1, 0], dtype=int64)

In [34]:
model.predict_proba(X_test[:10])

array([[8.89808572e-01, 1.10191428e-01],
       [9.89649746e-01, 1.03502544e-02],
       [9.76379361e-09, 9.99999990e-01],
       [4.39561439e-02, 9.56043856e-01],
       [8.95885742e-01, 1.04114258e-01],
       [9.90152488e-01, 9.84751151e-03],
       [4.68336260e-02, 9.53166374e-01],
       [4.56904694e-02, 9.54309531e-01],
       [2.83060567e-03, 9.97169394e-01],
       [9.34606681e-01, 6.53933189e-02]])

# Useing Spam datasets

In [1]:
# Spam datasets 
import pandas as pd
df = pd.read_csv('spam_ham_dataset.csv')
df.head()

,Unnamed: 0,label,text,label_num
0,605,ham,Subject: enron methanol ; meter # : 988291\r\n...,0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\r\n( see...",0
2,3624,ham,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1
4,2030,ham,Subject: re : indian springs\r\nthis deal is t...,0

In [2]:
df.groupby('label').describe()

      Unnamed: 0                                                         \
           count    mean          std     min      25%     50%      75%
label
ham       3672.0  1835.5  1060.159422     0.0   917.75  1835.5  2753.25
spam      1499.0  4421.0   432.868340  3672.0  4046.50  4421.0  4795.50

              label_num
          max     count mean  std  min  25%  50%  75%  max
label
ham    3671.0    3672.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
spam   5170.0    1499.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0

In [3]:
# label column changinh binary 
df['spam']=df['label'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

,Unnamed: 0,label,text,label_num,spam
0,605,ham,Subject: enron methanol ; meter # : 988291\r\n...,0,0
1,2349,ham,"Subject: hpl nom for january 9 , 2001\r\n( see...",0,0
2,3624,ham,"Subject: neon retreat\r\nho ho ho , we ' re ar...",0,0
3,4685,spam,"Subject: photoshop , windows , office . cheap ...",1,1
4,2030,ham,Subject: re : indian springs\r\nthis deal is t...,0,0

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.text, df.spam, test_size=0.25)

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[2, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [10]:
# use multinomialNB 
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count, y_train)

MultinomialNB()

In [11]:
emails = [
    'hpl nom for january 9 , 2001\r\n(see...',
    'indian springs\r\nthis deal is t...'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 0], dtype=int64)

In [13]:
X_test_count = v.transform(X_test)
model.score(X_test_count,y_test)

0.9752513534416086

In [14]:
# useing sklearn pipeline 
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [15]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [16]:
clf.score(X_test, y_test)

0.9752513534416086