Use sklearn.datasets iris flower dataset to train your model using logistic regression. You need to figure out accuracy of your model and use that to predict different samples in your test dataset. In iris dataset there are 150 samples containing following features,

1.Sepal Length 2.Sepal Width 3.Petal Lenght 4.Petal Width

Using above 4 features you will clasify a flower in one of the three categories,

1.Setosa 2.Versicolour 3.Virginica

https://www.integratedots.com/wp-content/uploads/2019/06/iris_petal-sepal-e1560211020463.png

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
%matplotlib inline

In [4]:
df = pd.read_csv('iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [6]:
X = df[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
X

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [8]:
y = df[['Species']]
y

            Species
0       Iris-setosa
1       Iris-setosa
2       Iris-setosa
3       Iris-setosa
4       Iris-setosa
..              ...
145  Iris-virginica
146  Iris-virginica
147  Iris-virginica
148  Iris-virginica
149  Iris-virginica

[150 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [10]:
X_train

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
101            5.8           2.7            5.1           1.9
71             6.1           2.8            4.0           1.3
61             5.9           3.0            4.2           1.5
62             6.0           2.2            4.0           1.0
95             5.7           3.0            4.2           1.2
..             ...           ...            ...           ...
127            6.1           3.0            4.9           1.8
103            6.3           2.9            5.6           1.8
149            5.9           3.0            5.1           1.8
75             6.6           3.0            4.4           1.4
12             4.8           3.0            1.4           0.1

[105 rows x 4 columns]

In [11]:
X_test

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
35             5.0           3.2            1.2           0.2
116            6.5           3.0            5.5           1.8
104            6.5           3.0            5.8           2.2
40             5.0           3.5            1.3           0.3
77             6.7           3.0            5.0           1.7
21             5.1           3.7            1.5           0.4
93             5.0           2.3            3.3           1.0
141            6.9           3.1            5.1           2.3
60             5.0           2.0            3.5           1.0
110            6.5           3.2            5.1           2.0
66             5.6           3.0            4.5           1.5
69             5.6           2.5            3.9           1.1
9              4.9           3.1            1.5           0.1
137            6.4           3.1            5.5           1.8
32             5.2           4.1            1.5           0.1
64             5.6           2.9            3.6           1.3
36             5.5           3.5            1.3           0.2
123            6.3           2.7            4.9           1.8
97             6.2           2.9            4.3           1.3
14             5.8           4.0            1.2           0.2
10             5.4           3.7            1.5           0.2
18             5.7           3.8            1.7           0.3
45             4.8           3.0            1.4           0.3
29             4.7           3.2            1.6           0.2
20             5.4           3.4            1.7           0.2
87             6.3           2.3            4.4           1.3
146            6.3           2.5            5.0           1.9
22             4.6           3.6            1.0           0.2
50             7.0           3.2            4.7           1.4
19             5.1           3.8            1.5           0.3
63             6.1           2.9            4.7           1.4
78             6.0           2.9            4.5           1.5
122            7.7           2.8            6.7           2.0
89             5.5           2.5            4.0           1.3
113            5.7           2.5            5.0           2.0
42             4.4           3.2            1.3           0.2
53             5.5           2.3            4.0           1.3
31             5.4           3.4            1.5           0.4
56             6.3           3.3            4.7           1.6
130            7.4           2.8            6.1           1.9
57             4.9           2.4            3.3           1.0
7              5.0           3.4            1.5           0.2
59             5.2           2.7            3.9           1.4
132            6.4           2.8            5.6           2.2
115            6.4           3.2            5.3           2.3

In [12]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [13]:
model.fit(X_train, y_train)

C:\Users\meraj\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\meraj\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [14]:
y_test

             Species
35       Iris-setosa
116   Iris-virginica
104   Iris-virginica
40       Iris-setosa
77   Iris-versicolor
21       Iris-setosa
93   Iris-versicolor
141   Iris-virginica
60   Iris-versicolor
110   Iris-virginica
66   Iris-versicolor
69   Iris-versicolor
9        Iris-setosa
137   Iris-virginica
32       Iris-setosa
64   Iris-versicolor
36       Iris-setosa
123   Iris-virginica
97   Iris-versicolor
14       Iris-setosa
10       Iris-setosa
18       Iris-setosa
45       Iris-setosa
29       Iris-setosa
20       Iris-setosa
87   Iris-versicolor
146   Iris-virginica
22       Iris-setosa
50   Iris-versicolor
19       Iris-setosa
63   Iris-versicolor
78   Iris-versicolor
122   Iris-virginica
89   Iris-versicolor
113   Iris-virginica
42       Iris-setosa
53   Iris-versicolor
31       Iris-setosa
56   Iris-versicolor
130   Iris-virginica
57   Iris-versicolor
7        Iris-setosa
59   Iris-versicolor
132   Iris-virginica
115   Iris-virginica

In [15]:
model.predict(X_test)

array(['Iris-setosa', 'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica',
       'Iris-virginica'], dtype=object)

In [16]:
model.score(X_test,y_test)

0.9777777777777777

In [17]:
y_predicted = model.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predicted)
cm

array([[17,  0,  0],
       [ 0, 15,  1],
       [ 0,  0, 12]], dtype=int64)